### PR TITLE
pull sending and awaiting out of the same loop

### LINKED ISSUE #26: Getting training session is very slow
Awaiting inside loop for beginning and end times. All requests need to be made before awaiting, otherwise network delay adds up.

### PR DESCRIPTION
**Pull request by ethanqm**
Intended to fix #26
Pairing the session times with their respective objects is O(n^2), but it beats the network delay by a mile.

### CODE REVIEW

**Comment by ethanqm** [comment]
OK, longest test was just over 4000ms, and it was another endpoint (which also benefited from these improvements). Earlier I had to increase timeouts to more than 6000ms, so this is a big improvement.
On my machine (where these tests run faster) it's an improvement of 200ms/25-33%

**Comment by quyenjd** [comment]
Instead of O(N^2), turn the arrays to objects where keys are what needs to be the same, then loop through keys of one object, and query the value on the other one.

```js
obj1 = Object.fromEntries(arr1.map(value => [value.keyNeedToBeTheSame, value]));
// obj2 = ...

for (const key in obj1) {
  // A check if obj2 has the same key. If you're already certain, remove it.
  if (Object.prototype.hasOwnProperty.call(obj2, key)) {
    // Do something with obj1[key] and obj2[key].
  }
}
```

This should be O(N).

**Comment by ethanqm** [comment]
Oh ok awesome. I'm gonna refactor a little bit too while I'm in here. getPlayerTrainingSessionsAPI and getTeamTrainingSessionsAPI only have one variable difference after removing redundant role management

**Comment by ethanqm** [comment]
Leaving refactored code commented, because Nhan may still want use it in some situation.
Ended up adding role management for admin, so I had to add some tests about that. More corner cases checked too.

**Review by ThanhNhan2002 — APPROVED** [review]
LGMT

**Pull request merged**
