### PR TITLE
Line Graph endpoint, interface and tests

### LINKED ISSUE #30: Create getTeamTrainingSession again

### PR DESCRIPTION
**Pull request by ethanqm**
Supports filtering the influxdb for playerNames, teamNames, sessionNames and measurement fields, and aggregating the data by a time in seconds and with reducers: 'mean' (default), 'median', 'mode', 'max' and 'min'.

Currently counting buildQuery's InfluxQuery input type as the request interface.
 { fields: [<one or many _field value/s in influx>] } is the minimum required request.
Examples are on postman.

### CODE REVIEW

**Comment by ethanqm** [comment]
No role management is done right now. The only requirement is that a user be logged in.
We'll have to think for a minute about the restrictions on the requests a user can make.

**Comment by ethanqm** [comment]
I ended up re-implementing getTeamsSessionsAPI too ( #30 ), but I didn't end up needing it. There's still no endpoint yet either, it's just there (so coverage is slightly lower).

It might make sense to move 'buildQueryHasPermissions()' to src/influxUtils.ts, but it's a really heavy function and should only really be needed for these graph requests. It requests a users sessions, teams, and those teams' players but only awaits those results if it needs to. 
I might sleep on it and see if I change my mind about it, but the tests are succeeding in less than 400ms some times, which is way better than I would've thought. Postman says more like 2500ms, but it's also printing and formatting the data in that time I think.


Anyway, I'm probably ready to merge this. It's plenty for the frontend to work with and report back issues. Again, I'm working late so well-rested-me may have different opinions, but just go for it

**Comment by ThanhNhan2002** [comment]
Just have a looked at your getTeamsSessionsAPI re-implementation. I will write the endpoint and test case for getTeamSessionsAPI. After we finish this API, I will tell the frontend team to use this one to display the training sessions on the team page.

**Comment by ethanqm** [comment]
MERGED TO BackendBranch

**Pull request closed without merging**
